version: "3.9"

volumes:
  postgres_data:
  static_data:
  media_data:

networks:
  my_network:
    driver: bridge

services:
  app:
    container_name: movie_app
    build:
      context: ./backend
    command: ./start.sh
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - static_data:/app/static
      - media_data:/app/media
    expose:
      - 8000
      - 8020
    env_file:
      - ./backend/.envs/.env
    networks:
      - my_network

  db:
    container_name: movie_db
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my_network

  nginx:
    image: nginx:1.26.1-alpine
    container_name: movie_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/correct_permissions.sh:/correct_permissions.sh
      - static_data:/usr/share/nginx/html/static
      - media_data:/usr/share/nginx/html/media
    command: ["sh", "/correct_permissions.sh"]
    ports:
      - 80:80
    networks:
      - my_network

    depends_on:
      - app